### PR TITLE
[do not merge] rebase expand-getblockstats

### PR DESCRIPTION
**Pull request by jnewbery**
https://github.com/bitcoin/bitcoin/pull/14802 improved the performance of the getblockstats RPC method by ~100x by using data from the undo files instead of txindex. It also removes the requirement to run txindex to generate certain statistics.

This branch rebases the expand-getblockstats patchset on master to take advantages of those performance improvements.

This PR is not for merging into master. It's here for review of the rebased commits. To review: verify that the commits in this PR achieve the same as the last 6 commits in the https://github.com/bitcoinops/bitcoin/tree/expand-getblockstats branch.

After review, I'll force push this branch to the https://github.com/bitcoinops/bitcoin/tree/expand-getblockstats branch. The existing expand-getblockstats is saved as a tag here: https://github.com/bitcoinops/bitcoin/releases/tag/0.1.

### CODE REVIEW

**Comment by jnewbery** [comment]
@0xB10C - you've mentioned that you're interested in helping with the dashboard. Would you like to help review this?

@bitschmidty - as mentioned on our call, this should be an easy review. We just need to ensure that this doesn't break the expanded `getblockstats` statistics.

We need to use this rebase since the dashboard currently can't catch up to tip - the `getblockstats` call is too slow.

**Comment by 0xB10C** [comment]
I ran `getblockstats` on the last ~8000 testnet blocks (1560000 - 1567974) on both the `expand-getblockstats` and the `2019-06-rebase-expand-getblockstats` branches diffing the hashes of the JSON output. Both branches output the same data for the tested blocks. 

I'll however test this again on mainnet in a few days once I have a spare machine with an indexed and not pruned blockchain.

**Comment by jnewbery** [comment]
Great. Thanks @0xB10C !

**Comment by jnewbery** [comment]
I've taken the updated tests and and bug fixes from https://github.com/bitcoinops/bitcoin/releases/tag/0.1.1 and applied them to the commits in this branch. I've also run the rpc_getblockstats.py test over this rebased version using the json file from https://github.com/bitcoinops/bitcoin/releases/tag/0.1.1, to verify that they output the same stats.

@bitschmidty @0xB10C : I plan to tag this as 0.2 tomorrow. Then let's deploy this to the dashboard.

**Comment by jnewbery** [comment]
Tagged as 0.2: https://github.com/bitcoinops/bitcoin/releases/tag/0.2

**Pull request closed without merging**
